---
kubernetes_package_repo_version: v1.36
kubernetes_package_version: ""
kubernetes_packages:
  - cri-tools
  - kubelet
  - kubeadm
  - kubectl

kubernetes_cri_socket: unix:///run/containerd/containerd.sock
kubernetes_api_server_bind_port: 6443
kubernetes_service_cidr: 10.96.0.0/12
kubernetes_dns_domain: cluster.local
kubernetes_admin_user: "{{ ansible_user }}"

helm_version: v4.2.2
helm_checksums:
  amd64: 9adafecab4d406853bba163a70e9f104f47dbbf65ce24b7653bae7e36150bcb6
  arm64: 78803142087a0069fa4b50d3f32a84d3ef25c14d1ee8a40fbccf86a6216d2f36

cilium_version: 1.19.5
cilium_pod_cidr: 10.244.0.0/16
