---
kubernetes_package_repo_version: v1.36
kubernetes_package_version: ""
kubernetes_packages:
  - cri-tools
  - kubelet
  - kubeadm
  - kubectl

kubernetes_cri_socket: unix:///run/containerd/containerd.sock
kubernetes_api_server_bind_port: 6443
kubernetes_service_cidr: 10.96.0.0/12
kubernetes_dns_domain: cluster.local
kubernetes_admin_user: "{{ ansible_user }}"

helm_version: v4.2.2
helm_checksum: 9adafecab4d406853bba163a70e9f104f47dbbf65ce24b7653bae7e36150bcb6

cilium_version: 1.19.5
cilium_pod_cidr: 10.244.0.0/16

flux_version: v2.9.3
flux_checksum: eae4e8608c0ade2bf4e8dec1669dbb6b0c28b5822b252d97feccfb4fb1181fd2
flux_namespace: flux-system
flux_components:
  - source-controller
  - kustomize-controller
  - helm-controller
  - notification-controller
flux_install_timeout: 5m
